[package]
name = "knien"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.4.0"
futures = "0.3.26"
lapin = "2.1.1"
pin-project = "1.0.12"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = {version = "1.25.0", features = ["full"] }
uuid = { version = "1.3.0", features = [ "v4" ] }
