version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: tg
      RABBITMQ_DEFAULT_PASS: secret
      RABBITMQ_LOGS: /dev/null
    ports: ["127.0.0.1:15673:15672", "127.0.0.1:5673:5672"]
    networks: [default]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
networks:
  default: ~
